### ISSUE TITLE
Preparation before compiling

### ISSUE THREAD

**Issue by nxuv** [al1-ce/jspp-compiler-extension#20]
Implements:

- [x] **PARTIALLY** #12 Alias injection (basic c macro, `visibility alias name = symbol;`)
- [x] #13 Global file module (`module name;` at top of file)
- [x] #14 String conversion
- [x] #15 Import conversion (std -> System)
- [ ] **NOT PLANNED FOR NOW** #16 D-style symbol imports (`import modulename: symbol;`)
- [x] #17 Alias struct to class & const to final
- [x] #19 If main file and contains `void main()` then execute it
- [ ] **NOT PLANNED FOR NOW** Import visibility (ak public for imports between modules)

**Comment by nxuv** [comment]
Closing as visibility is pointless since js++ always imports entire module
